### ISSUE TITLE
为何不使用netty实现呢？

### ISSUE THREAD

**Issue by biezhi** [junicorn/Hsn#1]

**Comment by adar-w** [comment]
造轮子项目。

**Comment by biezhi** [comment]
如果想造的好点，可以做一个静态blog的程序。比如hexo这样的

**Comment by adar-w** [comment]
本来是想做一个类似tomcat/jetty层面的容器的,由此涉及到NIO,就做了这个。
考虑基于它做个容器。

**Comment by biezhi** [comment]
直接使用NIO做web服务器的挑战还是蛮大的，需要做很多测试。。

**Comment by adar-w** [comment]
嗯。 实现基础还可行。补齐及可用性需要做大量工作。

**Comment by biezhi** [comment]
就像如果我写一个web框架不基于servlet实现而是自己写一个底层的话可靠性会更低。。用于项目的可能性就很小了。

**Comment by adar-w** [comment]
可靠性主要还是在于通信那块。 如果分两层，通信用netty，http处理层面至后面session构建,请求路由自己实现也是可行的。
